// ============================================================================
// Copyright BRAINTRIBE TECHNOLOGY GMBH, Austria, 2002-2022
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ============================================================================
package com.braintribe.model.processing.query.parser.impl.listener;

import com.braintribe.model.processing.query.parser.impl.DefaultSource;
import com.braintribe.model.processing.query.parser.impl.autogenerated.GmqlParser.EntityQueryContext;
import com.braintribe.model.processing.query.parser.impl.autogenerated.GmqlParser.EntityQueryHeadContext;
import com.braintribe.model.processing.query.parser.impl.autogenerated.GmqlParser.EntityQueryStartContext;
import com.braintribe.model.processing.query.parser.impl.context.QueryCustomContext;
import com.braintribe.model.processing.query.parser.impl.context.basetype.DefaultCustomContext;
import com.braintribe.model.query.EntityQuery;
import com.braintribe.model.query.Source;

public abstract class GmqlEntityQueryParserListener extends GmqlQueryParserListener {

	@Override
	public void enterEntityQuery(EntityQueryContext ctx) {
		EntityQuery query = $.entityQuery();
		setValue(ctx, new QueryCustomContext(query));
		enableQueryHeadParsing();
		enableDefaultSource();
	}

	@Override
	public void exitEntityQuery(EntityQueryContext ctx) {
		takeValue(ctx.entityQueryStart());
		takeValue(ctx.queryTailWhere());
		takeValue(ctx.queryTailOrderBy());
		takeValue(ctx.queryTailPagination());
		disableDefaultSource();

	}

	@Override
	public void exitEntityQueryStart(EntityQueryStartContext ctx) {
		EntityQuery query = (EntityQuery) ((QueryCustomContext) getValue(ctx.getParent()).cast()).getReturnValue();

		if (ctx.Distinct() != null) {
			query.setDistinct(true);
		}
		String entityTypeSignature = ((DefaultCustomContext) takeValue(ctx.entityQueryHead()).cast()).getReturnValue();
		query.setEntityTypeSignature(entityTypeSignature);

		// to avoid default rule handling to fire
		setValue(ctx, new DefaultCustomContext(""));
	}

	@Override
	public void exitEntityQueryHead(EntityQueryHeadContext ctx) {
		String entityTypeSignature = ((DefaultCustomContext) takeValue(ctx.identifier()).cast()).getReturnValue();

		Source source = DefaultSource.T.create();
		String alias = null;
		if (ctx.alias() != null) {
			alias = ((DefaultCustomContext) takeValue(ctx.alias()).cast()).getReturnValue();
		}
		registerSource( alias,  source);
		disableQueryHeadParsing();
		setValue(ctx, new DefaultCustomContext(entityTypeSignature));
	}

}
