name: Periodic hc.js

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"   # Every day 3:00 UCT

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: "hc-js-test"

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: |
          yarn install

      - name: Test
        run: |
          yarn test

      # https://github.com/marketplace/actions/junit-report-action
      - name: Create Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: "junit.xml"
          annotate_only: true
          include_passed: false
          detailed_summary: true

      - name: Save Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: "junit-results--${{ github.event.repository.name }}--#${{ github.run_number }}"
          path: "junit.xml"
          if-no-files-found: ignore
