name: Periodic hc.js

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"   # Every day 3:00 UCT

jobs:
  run:
    uses: hiconic-os/hiconic.ci.workflows/.github/workflows/npm-build.yaml@main
    with:
      publish: false
      working-directory: "hc-js-test"
